version: '3.8'

services:
  # Jaeger - Distributed tracing backend
  jaeger:
    image: jaegertracing/all-in-one:1.54.0
    ports:
      - "4317:4317"   # OTLP gRPC receiver (for OpenTelemetry)
      - "16686:16686" # Jaeger UI
      - "14268:14268" # Jaeger collector HTTP
      - "6831:6831/udp" # Jaeger agent (legacy)
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - LOG_LEVEL=info
    container_name: jaeger-phase4b
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  # Prometheus - Metrics collection and monitoring
  prometheus:
    image: prom/prometheus:v2.49.1
    ports:
      - "9090:9090"   # Prometheus UI
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    container_name: prometheus-phase4b
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  # Grafana - Visualization dashboard (optional)
  grafana:
    image: grafana/grafana:10.3.3
    ports:
      - "3000:3000"   # Grafana UI
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD:-changeme}
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus
    container_name: grafana-phase4b
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

volumes:
  prometheus-data:
  grafana-data:
