[project]
name = "autoclv"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "pandas>=2.0.0",
    "numpy>=1.24.0",
]

[tool.pytest.ini_options]
addopts = "--ignore=analytics"

[tool.setuptools]
package-dir = {"" = "."}

[tool.setuptools.packages.find]
include = ["customer_base_audit*"]
exclude = ["analytics", "analytics.*"]
